### ISSUE TITLE
Errors when loading stable diffusion. Invalid syntax in txt2vectorgfx.py

### ISSUE THREAD

**Issue by enotbert** [GeorgLegato/Txt2Vectorgraphics#19]
During the launch Stable Diffusion couldn't load the script.

The message itself: 
Error loading script: txt2vectorgfx.py
Traceback (most recent call last):
  File "D:\SD\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\SD\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\SD\stable-diffusion-webui\scripts\txt2vectorgfx.py", line 8
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

OS: Windows 10
Other than that, stable diffusion works as usual. No new controls are expected.

**Comment by enotbert** [comment]
Just copied the RAW file and it works!
